name: Build Package

on:
  workflow_dispatch:
  push:

env:
  PACKAGES_DIR : /home/runner/pkg
  KERNEL_DIR : ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
             mkdir -p ${{ env.PACKAGES_DIR }}
             docker run --rm \
              -v "$PACKAGES_DIR:/buildd" \
              -v "$KERNEL_DIR:/buildd/sources" \
              quay.io/droidian/build-essential:next-arm64 \
              bash -c '
                set -e
                cd /buildd/sources

                git config --global --add safe.directory /buildd/sources
                git fetch origin --tags
                git fetch --all --tags || true

                git show-ref | grep 6.5 || true

                RELENG_HOST_ARCH=arm64 releng-build-package
             '

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: /home/runner/pkg
